apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitops-repo-creds
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<tvoj-user>/kargo-demo-gitops.git
  username: BorisRadenkovic
  password: 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