apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitops-repo-creds
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/BorisRadenkovic/kargo-demo-gitops-local.git
  username: BorisRadenkovic
  password: CHANGE_ME_LOCALLY