apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo-app
  namespace: kargo-demo
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/borisradenkovic/kargo-demo-python-app
        imageSelectionStrategy: Lexical
        allowTagsRegexes:
          - ^RC-[0-9]+-\d{4}\.\d{2}\.\d{2}_\d{2}\.\d{2}\.\d{2}$