replicaCount: 1

image:
  repository: ghcr.io/borisradenkovic/kargo-demo-python-app
  pullPolicy: IfNotPresent
  tag: "main"

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: nginx
  host: ""
  path: /
  pathType: Prefix
  annotations: {}